---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: "{{ .Values.pgDatabaseName }}-daily-backup"
spec:
  immediate: true
  schedule: "{{ .Values.pgBackupSchedule }}"
  backupOwnerReference: cluster
  cluster:
    name: "{{ .Values.pgDatabaseName }}-pg"
