---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.pgDatabaseName }}-pg-creds"
type: Opaque
stringData:
  username: "{{ .Values.pgUsername }}"
  password: "{{ .Values.pgPassword }}"

---
apiVersion: v1
kind: Secret
metadata:
  name: slk-creds
type: Opaque
stringData:
  generalChannelId: "{{ .Values.slkGeneralChannelId }}"
  blogBotToken: "{{ .Values.slkBlogBotToken }}"
