---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    ingress:
      - hostname: template.ip812.com
        service: http://go-template-svc.go-template.svc.cluster.local:8080
      - hostname: blog.ip812.com
        service: http://blog-svc.blog.svc.cluster.local:8080
      - hostname: pgadmin.ip812.com
        service: http://pgadmin-svc.postgres.svc.cluster.local:8080
      - hostname: capacitor.ip812.com
        service: http://capacitor.capacitor.svc.cluster.local:9000
      - hostname: prometheus.ip812.com
        service: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
      # - hostname: grafana.ip812.com
      #   service: http://prometheus-stack-grafana.monitoring.svc.cluster.local:80
      - hostname: jaeger.ip812.com
        service: http://jaeger.tracing.svc.cluster.local:16686
      - service: http_status:404
