---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-template-deploy
  namespace: ip812
  labels:
    app: go-template
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-template
  template:
    metadata:
      labels:
        app: go-template
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: go-template
          image: 678468774710.dkr.ecr.eu-central-1.amazonaws.com/ip812/go-template:1.4.1
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APP_ENV
              value: prod
            - name: APP_DOMAIN
              value: template.ip812.com
            - name: APP_PORT
              value: "8080"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ip812-secrets
                  key: go_template_pg_name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ip812-secrets
                  key: pg_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ip812-secrets
                  key: pg_password
            - name: DB_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: ip812-secrets
                  key: pg_endpoint
            - name: DB_SSL_MODE
              # value: require
              value: disable
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: ip812-secrets
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ip812-secrets
                  key: aws_secret_access_key
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: ip812-secrets
                  key: aws_region
