---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    ingress:
      - hostname: shoot-work-01.ip812.com
        service: tcp://kubernetes.default.svc:443
        originRequest:
          proxyType: socks
      - hostname: blog.ip812.com
        service: http://blog-svc.blog.svc.cluster.local:8080
      - hostname: pgadmin.ip812.com
        service: http://pgadmin-svc.postgres.svc.cluster.local:8080
      - hostname: victoria-logs.ip812.com
        service: http://vls-victoria-logs-single-server.victoria-logs.svc:9428
      - hostname: victoria-traces.ip812.com
        service: http://vts-vt-single-server.victoria-logs.svc:10428
      - service: http_status:404
