---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: "{{ .Values.image }}"
          args:
            - "tunnel"
            - "run"
            - "--protocol"
            - "http2"
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-creds
                  key: tunnelToken
          livenessProbe:
            httpGet:
              path: /ready
              port: 20241
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
