---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  namespace: ip812
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      imagePullSecrets:
        - name: github-cr-secret
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: ip812-secrets
                  key: pg_endpoint
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ip812-secrets
                  key: pg_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ip812-secrets
                  key: pg_password
