---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: clickstack
  namespace: clickstack-operators
spec:
  interval: 10m0s         
  url: https://clickhouse.github.io/ClickStack-helm-charts
