---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: ip812
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
