- name: Install common utilities
  apt:
    name:
      - curl
      - wget
      - unzip
      - make
      - git
      - vim
      - tmux
      - jq
      - yq
      - gnupg
      - strace
    state: present

- name: Install bcc tools
  apt:
    name:
      - bpfcc-tools
      - libbpfcc
      - libbpfcc-dev
      - "{{ 'pve-headers' if 'pve' in ansible_facts['kernel'] else 'linux-headers-' + ansible_facts['kernel'].split('-', 1)[1] }}"
    state: present
