- name: Install common utilities
  apt:
    name:
      - curl
      - wget
      - unzip
      - make
      - git
      - vim
      - tmux
      - jq
      - yq
      - gnupg
      - strace
    state: present

- name: Install bcc tools
  apt:
    name:
      - bpfcc-tools
      - libbpfcc
      - libbpfcc-dev
      - "linux-headers-{{ ansible_kernel }}"
    state: present
