- name: Extract client-data from kubeconfig
  shell: |
    yq -r '.users[] | select(.name == "kubernetes-admin") | .user."client-certificate-data"' /root/.kube/config > /tmp/client-certificate-data.txt
    yq -r '.users[] | select(.name == "kubernetes-admin") | .user."client-key-data"' /root/.kube/config > /tmp/client-key-data.txt
  args:
    executable: /bin/bash

- name: Upload client-data to R2 bucket
  shell: |
    aws s3 cp /tmp/client-certificate-data.txt s3://{{ org }}-{{ env }}-work-01-kubeconfig-bucket/client-certificate-data.txt --endpoint-url https://{{ cf_account_id }}.r2.cloudflarestorage.com
    aws s3 cp /tmp/client-key-data.txt s3://{{ org }}-{{ env }}-work-01-kubeconfig-bucket/client-key-data.txt --endpoint-url https://{{ cf_account_id }}.r2.cloudflarestorage.com
  args:
    executable: /bin/bash
  environment:
    AWS_ACCESS_KEY_ID: "{{ backups_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ backups_secret_access_key }}"
    AWS_REQUEST_CHECKSUM_CALCULATION: when_required
    AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
  no_log: true

- name: Cleanup client-certificate-data tmp file
  file:
    path: /tmp/client-certificate-data.txt
    state: absent

- name: Cleanup client-key-data tmp file
  file:
    path: /tmp/client-key-data.txt
    state: absent
