# This file contains all resources related to the Cloudflare tunnels

#################################################################################
#                                   Variables                                   #
#################################################################################

# Generated by

variable "ip812_tunnel_name" {
  type      = string
  sensitive = true
}

# $ openssl rand -base64 64
variable "ip812_tunnel_secret" {
  type      = string
  sensitive = true
}

#################################################################################
#                                    Tunnels                                    #
#################################################################################

resource "cloudflare_zero_trust_tunnel_cloudflared" "ip812_tunnel" {
  account_id = var.cloudflare_account_id
  name       = var.ip812_tunnel_name
  secret     = var.ip812_tunnel_secret
}

resource "cloudflare_zero_trust_tunnel_cloudflared_config" "ip812_tunnel_cfg" {
  account_id = var.cloudflare_account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.ip812_tunnel.id
  config {
    ingress_rule {
      hostname = cloudflare_record.traefik_dns_record.hostname
      service  = "http://traefik:80"
    }
    ingress_rule {
      hostname = cloudflare_record.blog_dns_record.hostname
      service  = "http://traefik:80"
    }
    ingress_rule {
      service = "http_status:404"
    }
  }
}

