- name: Manage Proxmox WireGuard config
  hosts: proxmox
  become: yes
  gather_facts: yes
  vars:
    wg_server_private_key: "{{ wg_proxmox_private_key }}"
    wg_peers:
      - name: Work laptop
        public_key: "{{ wg_work_laptop_public_key }}"
        allowed_ips: 10.0.0.2/32
      - name: CI/CD
        public_key: "{{ wg_cicd_public_key }}"
        allowed_ips: 10.0.0.3/32
      - name: shoot-work-01
        public_key: "{{ wg_shoot_work_01_public_key }}"
        allowed_ips: 10.0.0.4/32
      - name: shoot-o11y-01
        public_key: "{{ wg_shoot_o11y_01_public_key }}"
        allowed_ips: 10.0.0.5/32
  tasks:
    - name: Render WireGuard server config
      template:
        src: templates/wg0.conf.j2
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: "0600"
      notify: Reload WireGuard

    - import_tasks: tasks/coredns.yml

  handlers:
    - name: Reload WireGuard
      ansible.builtin.shell: wg syncconf wg0 <(wg-quick strip wg0)
      args:
        executable: /bin/bash

    - name: Restart CoreDNS
      ansible.builtin.systemd:
        name: coredns
        state: restarted
        daemon_reload: yes
