---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}-deploy"
  labels:
    app: "{{ .Values.name }}" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.name }}"  
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"  
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: "{{ .Values.name }}"  
          image: "{{ .Values.image }}" 
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APP_ENV
              value: prod
            - name: APP_DOMAIN
              value: "{{ .Values.hostname }}"
            - name: APP_PORT
              value: "8080"
            - name: DB_NAME
              value: "{{ .Values.pgDatabaseName }}"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.pgDatabaseName }}-pg-creds" 
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.pgDatabaseName }}-pg-creds" 
                  key: password
            - name: DB_ENDPOINT
              value: "{{ .Values.pgHost }}"
            - name: DB_SSL_MODE
              # value: require
              value: disable
            - name: SLACK_GENERAL_CHANNEL_ID
              valueFrom:
                secretKeyRef:
                  name: slk-creds
                  key: generalChannelId
            - name: SLACK_BLOG_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slk-creds
                  key: blogBotToken
