---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.database }}-pg-creds"
type: Opaque
stringData:
  username: "{{ .Values.username }}"
  password: "{{ .Values.password }}"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: "{{ .Values.database }}-pg"
  annotations:
    cnpg.io/skipEmptyWalArchiveCheck: "enabled"
spec:
  imageName: "{{ .Values.image }}"
  instances: 1
  primaryUpdateStrategy: unsupervised
  enablePDB: false
  monitoring:
    enablePodMonitor: true
  storage:
    storageClass: local-path
    size: "{{ .Values.storageSize }}"
  bootstrap:
    {{- if .Values.isInit }}
    initdb:
      database: "{{ .Values.database }}"
      owner: "{{ .Values.database }}"
      secret:
        name: "{{ .Values.database }}-pg-creds"
    {{- else }}
    recovery:
      source: "{{ .Values.database }}-pg-backup"
      database: "{{ .Values.database }}"
      owner: "{{ .Values.database }}"
      secret:
        name: "{{ .Values.database }}-pg-creds"
    {{- end }}
  externalClusters:
    - name: "{{ .Values.database }}-pg-backup"
      barmanObjectStore:
        serverName: "{{ .Values.database }}-pg"
        destinationPath: "s3://{{ .Values.backupsBucket }}"
        s3Credentials:
          inheritFromIAMRole: true
  backup:
    barmanObjectStore:
      destinationPath: "s3://{{ .Values.backupsBucket }}"
      retentionPolicy: "{{ .Values.retentionPolicy }}"
      s3Credentials:
        inheritFromIAMRole: true
      wal:
        compression: gzip
      data:
        compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: "{{ .Values.database }}-daily-backup"
spec:
  immediate: true
  schedule: "{{ .Values.backupSchedule }}"
  backupOwnerReference: cluster
  cluster:
    name: "{{ .Values.database }}-pg"
