---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.pgDatabaseName }}-pg-creds"
type: Opaque
stringData:
  username: "{{ .Values.pgUsername }}"
  password: "{{ .Values.pgPassword }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockercConfigJSON | quote }}
