---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: opentelemetry-output
  labels:
    fluentbit.fluent.io/enabled: "true"
spec:
  match: "*"
  plugin: opentelemetry
  host: opentelemetry-collector-collector.opentelemetry-operator-system.svc
  port: 4318
  tls:
    enabled: false
    verify: false
  metrics_uri: /v1/metrics
  logs_uri: /v1/logs
  traces_uri: /v1/traces
  log_response_payload: true
  add_labels:
    app: fluent-bit
    color: blue
