---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: otel-http-output
spec:
  match: "*"
  otlp:
    host: opentelemetry-collector-collector.opentelemetry-operator-system.svc
    port: 4318
    uri: /v1/logs
