---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterParser
metadata:
  name: containerd-parser
  labels:
    fluentbit.fluent.io/enabled: "true"
    fluentbit.fluent.io/component: logging
spec:
  decoders:
  - decodeFieldAs: json log
  regex:
    regex: ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
    timeFormat: '%Y-%m-%dT%H:%M:%S.%L%z'
    timeKeep: true
    timeKey: time
