---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
      - name: cloudflared
        image: "cloudflare/cloudflared:2025.7.0"
        args:
          - "tunnel"
          - "--config"
          - "/etc/cloudflared/config/config.yaml"
          - "run"
          - "--protocol"
          - "http2"
        env:
          - name: TUNNEL_TOKEN
            valueFrom:
              secretKeyRef:
                name: cloudflared-creds
                key: TUNNEL_TOKEN
        volumeMounts:
          - name: config
            mountPath: /etc/cloudflared/config
        livenessProbe:
          httpGet:
            path: /ready
            port: 20241
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: cloudflared-config
