---
name: Ansible WireGuard Hub Prod

on:
  push:
    branches:
      - main
    paths:
      - ansible/wireguard-hub.yml
      - ansible/requirements.yml
      - ansible/tasks/coredns.yml
      - ansible/templates/wg0.conf.j2
      - ansible/templates/Corefile.j2
      - .github/workflows/ansible-wireguard-hub.yaml
  workflow_dispatch:

# Core Ansible jobs share the same WireGuard identity (10.0.0.3), so they should
# wait for each other.
concurrency:
  group: ansible-prod
  cancel-in-progress: false

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up WireGuard
        uses: ./.github/actions/wireguard
        with:
          cicd_private_key: ${{ secrets.WG_CICD_PRIVATE_KEY }}
          proxmox_public_key: ${{ secrets.WG_PROXMOX_PUBLIC_KEY }}

      - name: Install Ansible requirements
        run: ansible-galaxy install -r ansible/requirements.yml

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v9
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        with:
          playbook: ansible/wireguard-hub.yml
          key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}
          options: |
            --inventory ansible/inventory.ini
            --user root
            --extra-vars wg_proxmox_private_key=${{ secrets.WG_PROXMOX_PRIVATE_KEY }}
            --extra-vars wg_work_laptop_public_key=${{ secrets.WG_WORK_LAPTOP_PUBLIC_KEY }}
            --extra-vars wg_cicd_public_key=${{ secrets.WG_CICD_PUBLIC_KEY }}
            --extra-vars wg_shoot_work_01_public_key=${{ secrets.WG_SHOOT_WORK_01_PUBLIC_KEY }}
            --extra-vars wg_shoot_o11y_01_public_key=${{ secrets.WG_SHOOT_O11Y_01_PUBLIC_KEY }}
            --extra-vars wg_shoot_mgnt_01_public_key=${{ secrets.WG_SHOOT_MGNT_01_PUBLIC_KEY }}
            --extra-vars wg_cicd_shoot_work_01_public_key=${{ secrets.WG_CI_CD_SHOOT_WORK_01_PUBLIC_KEY }}
            --extra-vars wg_cicd_shoot_o11y_01_public_key=${{ secrets.WG_CI_CD_SHOOT_O11Y_01_PUBLIC_KEY }}
            --extra-vars wg_cicd_shoot_mgnt_01_public_key=${{ secrets.WG_CI_CD_SHOOT_MGNT_01_PUBLIC_KEY }}

      - name: Tear down WireGuard
        if: always()
        uses: ./.github/actions/wireguard-teardown
