---
name: Ansible Kubeadm Init

on:
  repository_dispatch:
    types: [kubeadm-init]

env:
  TARGET_VM: ${{ github.event.client_payload.target_vm }}

jobs:
  run-playbook:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up WireGuard
        uses: ./.github/actions/wireguard
        with:
          cicd_private_key: ${{ secrets.WG_CICD_PRIVATE_KEY }}
          proxmox_public_key: ${{ secrets.WG_PROXMOX_PUBLIC_KEY }}

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v9
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
        with:
          playbook: ansible/kubeadm-init.yml
          key: ${{ secrets.CICD_SSH_PRIVATE_KEY }}
          options: |
            --inventory ansible/inventory.ini
            --user root
            --extra-vars target=${{ env.TARGET_VM }}
            --extra-vars dp_token=${{ secrets.DP_TOKEN }}
            --extra-vars gh_access_token=${{ secrets.GH_ACCESS_TOKEN }}
            --extra-vars backups_access_key_id=${{ secrets.BACKUPS_ACCESS_KEY_ID }}
            --extra-vars backups_secret_access_key=${{ secrets.BACKUPS_SECRET_ACCESS_KEY }}
            --extra-vars cf_account_id=${{ secrets.CF_ACCOUNT_ID }}

      - name: Tear down WireGuard
        if: always()
        uses: ./.github/actions/wireguard-teardown
