---
name: Common Checkov Scan

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  checkov-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: common/
          quiet: true
          framework: terraform

      - name: Send Slack notification
        if: always()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLK_GITHUB_BOT_TOKEN }}
          SLACK_CHANNEL: terraform 
          CHECKOV_RESULT: ${{ steps.checkov.outcome }}
        run: |
          JOB_URL="https://github.com/ip812/infra/actions/runs/${GITHUB_RUN_ID}"

          if [ "${CHECKOV_RESULT}" = "success" ]; then
            STATUS="✅ Checkov scan passed"
            COLOR="#2eb886"
          else
            STATUS="❌ Checkov scan failed"
            COLOR="#e01e5a"
          fi

          curl -X POST "https://slack.com/api/chat.postMessage" \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"channel\": \"${SLACK_CHANNEL}\",
              \"attachments\": [
                {
                  \"color\": \"${COLOR}\",
                  \"title\": \"Checkov Scan\",
                  \"title_link\": \"${JOB_URL}\",
                  \"text\": \"${STATUS} in *common*\",
                }
              ]
            }"
