---
name: Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_TOKEN }}

      - name: Run Terraform Apply
        run: |
          cd prod
          terraform init -backend-config=backend-config.hcl
          terraform apply -auto-approve -backend-config="token=${secrets.TF_TOKEN}"
