name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - prod/**.tf  ## Ensure to only run when Terraform configuration changes

env:
  TF_CLOUD_ORGANIZATION: ip812 ## Replace with your HCP Terraform Organization name
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }} ## Replace with your HCP Terraform API Token stored in secrets
  TF_WORKSPACE: prod ## Replace with your existing Terraform workspace in HCP
  CONFIG_DIRECTORY: prod ## Adjust if necessary, the directory where your Terraform configuration is located

jobs:
  terraform-cloud-apply-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Upload Terraform Configuration to HCP
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Terraform Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}

      - name: Apply Terraform Run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        id: apply
        if: ${{ fromJSON(steps.create-run.outputs.payload).data.attributes.actions.IsConfirmable }}
        with:
          run: ${{ steps.create-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"

