---
name: K8s Image Updater

on:
  repository_dispatch:
    types: [update-image]

env:
  IMAGE_NAME: ${{ github.event.client_payload.image_name }}
  IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
  COMMIT_URL: ${{ github.event.client_payload.commit_url }}

jobs:
  update-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update K8s manifests
        run: |
          git config --global user.name "Image Updater"
          git config --global user.email "bot.imageupdater@ip812.com"
          find prod-k8s -type f -name "*.tf" -exec sed -i "s|${{ env.IMAGE_NAME }}:.*|${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|" {} +
          git add .
          git commit -m "cicd: Update image ${{ env.IMAGE_NAME }} to version ${{ env.IMAGE_TAG }}"
          git push origin main
  trigger-k8s-deploy:
    needs: update-image
    runs-on: ubuntu-latest
  
    steps:
      - name: Trigger K8s Deploy
        run: |
          curl -X POST https://api.github.com/repos/avalonpharma/infra/actions/workflows/k8s-deploy.yaml/dispatches \
          -H "Authorization: token ${{ secrets.GH_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          -d '{
            "ref": "main"
          }'
