---
name: Infra Apply

on:
  push:
    branches:
      - main
    paths:
      - '**/*.tf'

env:
  TF_VAR_aws_access_key_id: ${{ secrets.TF_VAR_AWS_ACCESS_KEY_ID }}
  TF_VAR_aws_secret_access_key: ${{ secrets.TF_VAR_AWS_SECRET_ACCESS_KEY }}
  TF_VAR_cf_account_id: ${{ secrets.TF_VAR_CF_ACCOUNT_ID }}
  TF_VAR_cf_api_token: ${{ secrets.TF_VAR_CF_API_TOKEN }}
  TF_VAR_cf_ip812_zone_id: ${{ secrets.TF_VAR_CF_IP812_ZONE_ID }}
  TF_VAR_cf_tunnel_secret: ${{ secrets.TF_VAR_CF_TUNNEL_SECRET }}
  TF_VAR_gf_cloud_access_policy_token: ${{ secrets.TF_VAR_GF_CLOUD_ACCESS_POLICY_TOKEN }}
  TF_VAR_gh_access_token: ${{ secrets.TF_VAR_GH_ACCESS_TOKEN }}
  TF_VAR_k8s_client_certificate: ${{ secrets.TF_VAR_K8S_CLIENT_CERTIFICATE }}
  TF_VAR_k8s_client_key: ${{ secrets.TF_VAR_K8S_CLIENT_KEY }}
  TF_VAR_k8s_cluster_ca_certificate: ${{ secrets.TF_VAR_K8S_CLUSTER_CA_CERTIFICATE }}
  TF_VAR_pg_password: ${{ secrets.TF_VAR_PG_PASSWORD }}
  TF_VAR_pg_username: ${{ secrets.TF_VAR_PG_USERNAME }}
  TF_VAR_slk_github_bot_token: ${{ secrets.TF_VAR_SLK_GITHUB_BOT_TOKEN }}
  TF_VAR_ts_auth_key: ${{ secrets.TF_VAR_TS_AUTH_KEY }}

jobs:
  infra-apply:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TS_AUTH_KEY }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.6"

      - name: Terraform Init
        run: terraform init
        working-directory: ./prod

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./prod

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./prod
