---
name: Prod Drift Check 

# on:
#   schedule:
#     - cron: '*/5 * * * *'

on:
  push:
    branches:
      - main

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.ORG }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  terraform-cloud-drift-check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Upload Terraform configuration to HCP
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload
        with:
          workspace: prod
          directory: prod 

      - name: Create Terraform create run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          workspace: prod
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Create Terraform plan output 
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.3.2
        id: plan-output
        with:
          plan: ${{ steps.create-run.outputs.plan_id }}

      
      - name: Check if plan matches expected values
        id: check-plan
        run: |
          add="${{ steps.plan-output.outputs.add }}"
          change="${{ steps.plan-output.outputs.change }}"
          destroy="${{ steps.plan-output.outputs.destroy }}"
          plan_status="${{ steps.plan-output.outputs.plan_status }}"
          status="${{ steps.plan-output.outputs.status }}"

          if [[ "$add" == "0" && "$change" == "0" && "$destroy" == "0" && "$plan_status" == "finished" && "$status" == "Success" ]]; then
            echo "Plan is valid. No drift detected."
          else
            echo "Drift detected or invalid plan. Values: add=$add, change=$change, destroy=$destroy, plan_status=$plan_status, status=$status"
            exit 1
          fi

      - name: Send Slack notification
        if: always()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLK_GITHUB_BOT_TOKEN }}
          SLACK_CHANNEL: terraform 
          DRIFT_CHECK_RESULT: ${{ steps.check-plan.outcome }}
        run: |
          RUN_URL="https://github.com/ip812/infra/actions/runs/${GITHUB_RUN_ID}"
          curl --header "Authorization: Bearer $TF_API_TOKEN" https://app.terraform.io/api/v2/plans/${{ steps.create-run.outputs.plan_id }}

          if [ "${DRIFT_CHECK_RESULT}" = "success" ]; then
            STATUS="✅ Drift check passed"
            COLOR="#2eb886"
          else
            STATUS="❌ Drift check failed"
            COLOR="#e01e5a"
          fi

          curl -X POST "https://slack.com/api/chat.postMessage" \
            -H "Authorization: Bearer $SLACK_BOT_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{
              \"channel\": \"${SLACK_CHANNEL}\",
              \"attachments\": [
                {
                  \"color\": \"${COLOR}\",
                  \"title\": \"Drift check\",
                  \"title_link\": \"${RUN_URL}\",
                  \"text\": \"${STATUS} in *prod*\",
                }
              ]
            }"
