---
name: Prod Drift Check 

on:
  schedule:
    - cron: '*/5 * * * *'

env:
  TF_CLOUD_ORGANIZATION: ${{ vars.ORG }}
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  terraform-cloud-drift-check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Upload Terraform configuration to HCP
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload
        with:
          workspace: prod
          directory: prod 

      - name: Create Terraform create run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          workspace: prod
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}

      - name: Create Terraform plan output 
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.3.2
        id: plan-output
        with:
          plan: ${{ steps.run.outputs.plan_id }}

      - name: Reference plan output
        run: |
          echo "Plan status: ${{ steps.plan-output.outputs.plan_status }}"
          echo "Resources to Add: ${{ steps.plan-output.outputs.add }}"
          echo "Resources to Change: ${{ steps.plan-output.outputs.change }}"
          echo "Resources to Destroy: ${{ steps.plan-output.outputs.destroy }}"
