---
name: Prod Checkov Scan

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  checkov-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: prod/
          quiet: true
          framework: terraform
