---
name: Terraform Apply Prod

on:
  push:
    branches:
      - main
    paths:
      - terraform/prod/**

env:
  TF_CLOUD_ORGANIZATION: ip812
  TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

jobs:
  apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Upload Terraform configuration to HCP
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: upload
        with:
          workspace: prod
          directory: terraform/prod

      - name: Create Terraform apply run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: create-run
        with:
          workspace: prod
          configuration_version: ${{ steps.upload.outputs.configuration_version_id }}

      - name: Apply Terraform run
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        id: apply
        if: ${{ fromJSON(steps.create-run.outputs.payload).data.attributes.actions.IsConfirmable }}
        with:
          run: ${{ steps.create-run.outputs.run_id }}
