---
name: Update Lambda trigger

on:
  repository_dispatch:
    types: [update-lambda-trigger]

env:
  IMAGE_NAME: ${{ github.event.client_payload.image_name }}
  IMAGE_TAG: ${{ github.event.client_payload.image_tag }}
  COMMIT_URL: ${{ github.event.client_payload.commit_url }}

jobs:
  update-lambda-trigger:
    runs-on: ubuntu-24.04

    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Lambda tag
        run: |
          sed -i "s|${{ env.IMAGE_NAME }}:.*|${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}\"|" prod/lambdas.tf

      - name: Commit changes
        run: |
          git config --global user.name 'deployer[bot]'
          git config --global user.email 'deployer[bot]@users.noreply.${{ vars.ORG }}.com'
          git remote set-url origin https://github-actions:${{ secrets.GH_ACCESS_TOKEN }}@github.com/${{ vars.ORG }}/infra.git
          git add prod/lambdas.tf
          git commit -m "Update Lambda ${{ env.IMAGE_NAME }} to the latest tag ${{ env.IMAGE_TAG }}"
          git push origin main

      - name: Trigger deploy pipeline 
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          repository: "ip812/infra"
          event-type: update-lambda
          client-payload: |
            {
              "image_name": "${{ env.IMAGE_NAME }}",
              "image_tag": "${{ env.IMAGE_TAG }}",
              "commit_url": "${{ env.COMMIT_URL }}"
            }
